@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "dipl.danai.app.controller.GymController#typeOfWorkouts(Model,Authentication)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "dipl.danai.app.controller.GymController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_95350649 { 
   	label=danai
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1386287572 { 
   	label=app
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1066783008 { 
   	label=WorkoutService
	labeljust=l
	fillcolor=white
	style=filled
   
   WorkoutService823322234XXXfindAll0[
	label="+ findAll()"
	style=filled
	fillcolor=white
	tooltip="WorkoutService

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1790884350 { 
   	label=GymService
	labeljust=l
	fillcolor=white
	style=filled
   
   GymService823322234XXXgetGymByEmail1808118735[
	label="+ getGymByEmail()"
	style=filled
	fillcolor=white
	tooltip="GymService

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_224331244 { 
   	label=GymController
	labeljust=l
	fillcolor=white
	style=filled
   
   GymController967126229XXXtypeOfWorkouts56750613[
	label="+ typeOfWorkouts()"
	style=filled
	fillcolor=white
	tooltip="GymController

null"
	penwidth=4
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
GymController967126229XXXtypeOfWorkouts56750613 -> GymService823322234XXXgetGymByEmail1808118735;
GymController967126229XXXtypeOfWorkouts56750613 -> WorkoutService823322234XXXfindAll0;
    
}
@enduml